import { useState } from 'react';
import { toast } from 'react-toastify';
import { useResume } from '../../context/ResumeContext';
import api from '../../services/api';

const EMPTY = { company: '', role: '', duration: '', description: '', bullets: [] };

export default function Experience() {
  const { resume, updateExperience } = useResume();
  const items = resume.experience;
  const [improving, setImproving] = useState({});

  const update = (i, field, value) =>
    updateExperience(items.map((item, idx) => idx === i ? { ...item, [field]: value } : item));

  const add = () => updateExperience([...items, { ...EMPTY, bullets: [] }]);
  const remove = (i) => updateExperience(items.filter((_, idx) => idx !== i));

  const handleImproveBullets = async (i) => {
    const item = items[i];
    if (!item.description) return toast.error('Add a description first');
    setImproving({ ...improving, [i]: true });
    try {
      const res = await api.post('/ai/improve-bullets', {
        description: item.description,
        role: item.role,
        company: item.company,
      });
      update(i, 'bullets', res.data.bullets);
      toast.success('Bullets generated by AI ✨');
    } catch {
      toast.error('AI improvement failed');
    } finally {
      setImproving({ ...improving, [i]: false });
    }
  };

  return (
    <div className="space-y-5">
      <div className="flex items-start gap-3 p-3 bg-primary/5 border border-primary/20 rounded-xl">
        <span className="text-lg shrink-0">💡</span>
        <p className="text-xs text-ink-muted leading-relaxed">
          <span className="font-semibold text-ink">Fresh grad?</span> No worries — this step is fully optional. Skip it and focus on your projects and skills instead.
        </p>
      </div>

      {items.map((item, i) => (
        <div key={i} className="card space-y-4 relative group">
          {items.length > 1 && (
            <button
              onClick={() => remove(i)}
              className="absolute top-4 right-4 w-6 h-6 rounded-lg bg-danger/10 text-danger hover:bg-danger/20 transition-all flex items-center justify-center text-sm opacity-0 group-hover:opacity-100"
            >×</button>
          )}
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 bg-primary/10 rounded-lg flex items-center justify-center text-primary text-xs font-bold">{i + 1}</div>
            <p className="text-xs font-bold text-ink-muted uppercase tracking-widest">Experience #{i + 1}</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="label">Company <span className="optional-tag">(optional)</span></label>
              <input className="input" placeholder="DecodeLabs" value={item.company} onChange={(e) => update(i, 'company', e.target.value)} />
            </div>
            <div>
              <label className="label">Role <span className="optional-tag">(optional)</span></label>
              <input className="input" placeholder="Frontend Developer Intern" value={item.role} onChange={(e) => update(i, 'role', e.target.value)} />
            </div>
            <div className="sm:col-span-2">
              <label className="label">Duration <span className="optional-tag">(optional)</span></label>
              <input className="input" placeholder="Jan 2026 – Present" value={item.duration} onChange={(e) => update(i, 'duration', e.target.value)} />
            </div>
            <div className="sm:col-span-2">
              <div className="flex items-center justify-between mb-1.5">
                <label className="label mb-0">Description <span className="optional-tag">(optional)</span></label>
                <button onClick={() => handleImproveBullets(i)} disabled={improving[i]} className="ai-btn">
                  {improving[i] ? (
                    <span className="flex items-center gap-1.5">
                      <span className="w-3 h-3 border border-success border-t-transparent rounded-full animate-spin" />
                      Generating…
                    </span>
                  ) : '✨ AI Bullets'}
                </button>
              </div>
              <textarea
                className="textarea"
                rows={3}
                placeholder="Describe your responsibilities and achievements. AI will convert this into powerful bullet points..."
                value={item.description}
                onChange={(e) => update(i, 'description', e.target.value)}
              />
            </div>

            {item.bullets?.length > 0 && (
              <div className="sm:col-span-2 space-y-2">
                <div className="flex items-center gap-2">
                  <label className="label mb-0">AI Bullets</label>
                  <span className="badge-success text-xs">Generated</span>
                </div>
                {item.bullets.map((b, bi) => (
                  <div key={bi} className="flex items-center gap-2">
                    <span className="text-primary text-sm shrink-0">•</span>
                    <input
                      className="input py-1.5 text-xs"
                      value={b}
                      onChange={(e) => {
                        const newBullets = [...item.bullets];
                        newBullets[bi] = e.target.value;
                        update(i, 'bullets', newBullets);
                      }}
                    />
                    <button
                      onClick={() => update(i, 'bullets', item.bullets.filter((_, bIdx) => bIdx !== bi))}
                      className="text-ink-faint hover:text-danger transition-colors shrink-0 text-lg leading-none"
                    >×</button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      ))}

      <button onClick={add} className="btn-ghost w-full justify-center gap-2 border-dashed">
        + Add Another Experience
      </button>
    </div>
  );
}